version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: local-postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: local-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.kube:/home/jenkins/.kube
      - ~/.minikube:/home/jenkins/.minikube
volumes:
  pgdata: {}
  jenkins_home: {}
